import torch
import torch.nn as nn
import math
import warnings
import collections.abc
from itertools import repeat
from einops import rearrange

# --------------------------------------------------------------------------------
# From basicsr/arch_util.py / timm
# --------------------------------------------------------------------------------

def _ntuple(n):
    def parse(x):
        if isinstance(x, collections.abc.Iterable) and not isinstance(x, str):
            return tuple(x)
        return tuple(repeat(x, n))
    return parse

to_2tuple = _ntuple(2)

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor

def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

def drop_path(x, drop_prob: float = 0., training: bool = False):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/drop.py
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0], ) + (1, ) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output

class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    """
    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)

# --------------------------------------------------------------------------------
# FIPER Specific Utils
# --------------------------------------------------------------------------------

class LayerNorm2D(nn.Module):
    def __init__(self, normalized_shape, eps = 1e-6, group = 1):
        super().__init__()
        self.weight = nn.Parameter(torch.ones(normalized_shape))
        self.bias = nn.Parameter(torch.zeros(normalized_shape))
        self.group = group
        self.eps = eps
        self.normalized_shape = (normalized_shape,)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # Expected input: B C H W
        # If group > 1, it rearranges channels.
        if self.group > 1:
            x = rearrange(x, 'b (g c) h w -> (b g) c h w', g = self.group)
        
        u = x.mean(1, keepdim = True)
        s = (x - u).pow(2).mean(1, keepdim = True)
        x = (x - u) / torch.sqrt(s + self.eps)
        
        if self.group > 1:
            x = rearrange(x, '(b g) c h w -> b (g c) h w', g = self.group)
            
        x = self.weight[:, None, None] * x + self.bias[:, None, None]
        return x

def grid_mapping(positions, freq_bands, aabb):
    """
    positions: tensor of coordinates
    freq_bands: frequency bands (scale factors)
    aabb: axis aligned bounding box [[min_x, min_y], [max_x, max_y]]
    """
    if freq_bands.ndim == 2 and freq_bands.shape[-1] == 3:
        freq_bands = freq_bands.transpose(0, 1).contiguous()
    
    # Check dimensions to ensure compatibility
    # Ensure aabb and freq_bands are on the same device as positions
    if aabb.device != positions.device:
        aabb = aabb.to(positions.device)
    if freq_bands.device != positions.device:
        freq_bands = freq_bands.to(positions.device)

    aabbSize = max(aabb[1] - aabb[0])
    scale = aabbSize[..., None] / freq_bands
    
    # Calculate local positions
    # positions shape: ..., 2 (or 3)
    # aabb shape: 2, 2
    # scale shape: ..., n_freqs
    
    pts_local = (positions - aabb[0])[..., None] % scale
    pts_local = pts_local / (scale / 2) - 1
    
    return pts_local
